name: "Build Packages"
on:
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.LIBRARIES_IO_API_KEY }}
  JOBS: 5

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: data
        fetch-depth: 1

    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          max-jobs = 10

    - name: Eval and Build Packages
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        nix flake lock --update-input dream2nix
        nix run .#build-all
        git add ./errors.json ./stats.json
        git commit -m "eval and build - $(date --rfc-3339=seconds)"
        git push --set-upstream origin data
