name: "Index and Translate"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

env:
  API_KEY: ${{ secrets.LIBRARIES_IO_API_KEY }}
  JOBS: 10

jobs:
  regenerate-index:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 1

    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          max-jobs = 10

    - name: Index and Translate
      run: |
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        nix run .#ci-job-all
        git push --set-upstream origin data
